name: Release

on:
  workflow_call:
    inputs:
      tag:
        description: "What tag to make a release for"
        required: true
        type: string
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set variables
        id: vars
        run: |
          if ${{ startsWith(github.ref, 'refs/tags/') }}; then
            # https://unix.stackexchange.com/a/325492
            ref="${{ github.ref }}"
            version_tag=${ref##*/}
          else
            version_tag=${{ inputs.tag }}
          fi
          echo "tag=${version_tag}" >> $GITHUB_OUTPUT
          echo "zipfile=cropseedstage_${version_tag:1}.zip" >> $GITHUB_OUTPUT
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: '${{ steps.vars.outputs.tag }}'
      - name: Install tools
        uses: asdf-vm/actions/install@v4
      # TODO: needs dotnet
      - name: Build zip
        run: ./build.sh
      - name: Make release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.vars.outputs.tag }}
          files: Releases/cropseedstage_${{ steps.vars.outputs.zipfile}}.zip
