name: Release

on:
  workflow_call:
    inputs:
      tag:
        description: "What tag to make a release for"
        required: true
        type: string
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Get tag
        id: tag
        run: |
          if ${{ startsWith(github.ref, 'refs/tags/') }}; then
            # https://unix.stackexchange.com/a/325492
            ref="${{ github.ref }}"
            echo "::set-output name=tag::${ref##*/}"
          else
            echo "::set-output name=tag::${{ inputs.tag }}"
          fi
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: '${{ steps.tag.outputs.tag }}'
      - name: Install tools
        uses: asdf-vm/actions/install@v2
      - name: Build zip
        run: ./build.sh
      - name: Make release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          files: Releases/cropseedstage_${{ steps.tag.outputs.tag}}.zip
